Repository tgspn/gestao-financeira-doo, pull requests merged in 2020-08, with the labels that each got.

#67 Stop to change the database
  GestaoFinanceira/GestaoFinanceira/Controllers/DashBoardController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/ReportController.cs
  GestaoFinanceira/GestaoFinanceira/GestaoFinanceira.csproj
  GestaoFinanceira/GestaoFinanceira/Model/EntryExpenses.cs
  GestaoFinanceira/GestaoFinanceira/Model/Report.cs
  GestaoFinanceira/GestaoFinanceira/Properties/Resources.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Properties/Resources.resx
  GestaoFinanceira/GestaoFinanceira/Resources/search (1).png
  GestaoFinanceira/GestaoFinanceira/Resources/search.png
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.resx
  GestaoFinanceira/GestaoFinanceira/Views/FrmEntryExpenses.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListEntryRevenue.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListEntryRevenue.resx
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.resx
Labels: Relatório

#69 feat(Report): Edit report
  GestaoFinanceira/GestaoFinanceira/Controllers/ReportController.cs
  GestaoFinanceira/GestaoFinanceira/Enums/Enums.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmCategories.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmReport.resx
Labels: Relatório

#71 Feito melhorias de DAO, Categorias, abrir despesas, gráficos de categoria.
  GestaoFinanceira/GestaoFinanceira/Controllers/AccountController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/CategoriesController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/CreditCardController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/DashBoardController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/EntryExpensesController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/PaymentMethodController.cs
  GestaoFinanceira/GestaoFinanceira/Controllers/ReportController.cs
  GestaoFinanceira/GestaoFinanceira/Model/Account.cs
  GestaoFinanceira/GestaoFinanceira/Model/CreditCard.cs
  GestaoFinanceira/GestaoFinanceira/Model/PaymentMethod.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmCategories.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmCategories.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmCategories.resx
  GestaoFinanceira/GestaoFinanceira/Views/FrmCreditCard.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmCreditCard.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmEntryExpenses.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmEntryExpenses.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCategories.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCategories.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCategories.resx
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCreditCard.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCreditCard.resx
  GestaoFinanceira/GestaoFinanceira/Views/FrmListEntryRevenue.cs
Labels: BD, Cartão de Crédito, Categoria, Receitas, contas-bancaria, dashboard, despesas

#73 fix (dashboar) : fix update dashboard
  GestaoFinanceira/GestaoFinanceira/Controllers/DashBoardController.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.cs
Labels: dashboard

#90 Database initialize
  GestaoFinanceira/GestaoFinanceira/App.config
  GestaoFinanceira/GestaoFinanceira/BD/Conections/BDInitializer.cs
  GestaoFinanceira/GestaoFinanceira/GestaoFinanceira.csproj
  GestaoFinanceira/GestaoFinanceira/Program.cs
  GestaoFinanceira/GestaoFinanceira/Properties/Resources.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Properties/Resources.resx
  GestaoFinanceira/GestaoFinanceira/Resources/splashscrean.gif
  GestaoFinanceira/GestaoFinanceira/Utils/CategoriesDefault.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmDashBoard.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmSplashScreen.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmSplashScreen.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmSplashScreen.resx
Labels: BD

#95 Allow Edit subcategories from list
  GestaoFinanceira/GestaoFinanceira/Controllers/CategoriesController.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCategories.Designer.cs
  GestaoFinanceira/GestaoFinanceira/Views/FrmListCategories.cs
Labels: subcategoria
